services:
  signalr-web:
    expose:
      - 80
    env_file:
      - .env
    scale: 2

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - signalr-web
    ports:
      - "8080:4000"